// SPIKE, not a screensaver: a sphere-traced distance field, 32 steps
// (dither 0, far cap 1, bound 0), to measure what marching costs.
//
// Generated by Scripts/raymarch-budget.sh from docs/raymarch-budget/march.glsl.in;
// edit the template, not this file. The scene is deliberately plain - a
// sphere, a torus, a box and a floor - so the cost is the march and nothing
// else. Everything is a function of iTime and fragCoord.
//
// The four knobs the spike varies, one at a time:
//   STEPS   the loop bound; the naive cost is proportional to it
//   DITHER  start each ray a hash-chosen fraction of a step in, so few steps
//           look like many
//   CAP     stop once the ray is past FAR; a ray to the sky then costs one
//           test instead of the full loop
//   BOUND   test the ray against a sphere around the scene first and skip the
//           march entirely on a miss

const int STEPS = 32;
const int DITHER = 0;
const int CAP = 1;
const int BOUND = 0;

const float FAR = 20.0;
const float HIT = 0.002;
const float BOUND_RADIUS = 4.5;

float hash21(vec2 p) {
    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453123);
}

float sdSphere(vec3 p, float r) { return length(p) - r; }
float sdTorus(vec3 p, vec2 t) { vec2 q = vec2(length(p.xz) - t.x, p.y); return length(q) - t.y; }
float sdBox(vec3 p, vec3 b) { vec3 q = abs(p) - b; return length(max(q, 0.0)) + min(max(q.x, max(q.y, q.z)), 0.0); }

float scene(vec3 p) {
    float floorPlane = p.y + 1.0;
    float sphere = sdSphere(p - vec3(1.4, 0.0, 0.0), 1.0);
    float torus = sdTorus(p - vec3(-1.4, -0.3, 0.0), vec2(1.0, 0.3));
    float box = sdBox(p - vec3(0.0, 0.2, -1.8), vec3(0.6));
    return min(min(floorPlane, sphere), min(torus, box));
}

vec3 normalAt(vec3 p) {
    vec2 e = vec2(0.001, 0.0);
    return normalize(vec3(
        scene(p + e.xyy) - scene(p - e.xyy),
        scene(p + e.yxy) - scene(p - e.yxy),
        scene(p + e.yyx) - scene(p - e.yyx)));
}

// Distance along the ray to a sphere of BOUND_RADIUS at the origin, or -1.
float boundEntry(vec3 ro, vec3 rd) {
    float b = dot(ro, rd);
    float c = dot(ro, ro) - BOUND_RADIUS * BOUND_RADIUS;
    float h = b * b - c;
    if (h < 0.0) return -1.0;
    return max(0.0, -b - sqrt(h));
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = (fragCoord - 0.5 * iResolution.xy) / iResolution.y;
    uv.y = -uv.y;

    float angle = iTime * 0.3;
    vec3 ro = vec3(7.5 * sin(angle), 2.2, 7.5 * cos(angle));
    vec3 forward = normalize(-ro + vec3(0.0, -0.2, 0.0));
    vec3 right = normalize(cross(forward, vec3(0.0, 1.0, 0.0)));
    vec3 up = cross(right, forward);
    vec3 rd = normalize(forward * 1.6 + right * uv.x + up * uv.y);

    vec3 sky = mix(vec3(0.08, 0.10, 0.18), vec3(0.30, 0.38, 0.55), uv.y + 0.5);
    vec3 color = sky;

    float t = 0.0;
    bool march = true;
    if (BOUND == 1) {
        float entry = boundEntry(ro, rd);
        if (entry < 0.0) march = false; else t = entry;
    }
    if (DITHER == 1) {
        t += hash21(fragCoord) * 0.1;
    }

    if (march) {
        bool hit = false;
        for (int i = 0; i < STEPS; i++) {
            float d = scene(ro + rd * t);
            if (d < HIT) { hit = true; break; }
            t += d;
            if (CAP == 1 && t > FAR) break;
        }
        if (hit) {
            vec3 p = ro + rd * t;
            vec3 n = normalAt(p);
            vec3 light = normalize(vec3(0.6, 0.9, 0.4));
            float diffuse = max(dot(n, light), 0.0);
            vec3 albedo = p.y < -0.99 ? vec3(0.55, 0.50, 0.45) : vec3(0.85, 0.35, 0.25);
            color = albedo * (0.15 + 0.85 * diffuse);
            color = mix(color, sky, 1.0 - exp(-t * 0.08));
        }
    }

    fragColor = vec4(color, 1.0);
}
